{
 "title": "Infra Full Stack — Application Dashboard",
 "tags": [
  "flask",
  "infra-full-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(up{job=\"flask-app\"} == 1)",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "App Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "max(app_uptime_seconds)", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "App Up/Down Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}